#!/usr/bin/env -S python3 -u
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "src"))

from Fushi.engine import Engine
from Fushi.uci import UCIHandler
from Fushi.evaluate import ShannonEvaluator, WeightedEvaluator
from Fushi.book import PolyglotBookReader
from Fushi.search import AlphaBetaSearcher, TranspositionTable, BookSearcher


def main():
    sys.stdin = os.fdopen(sys.stdin.fileno(), "r", buffering=1)
    sys.stdout = os.fdopen(sys.stdout.fileno(), "w", buffering=1)
    sys.stderr = os.fdopen(sys.stderr.fileno(), "w", buffering=1)

    evaluator = WeightedEvaluator(
        [
            (ShannonEvaluator(), 1.0),
            # (PSTEvaluator(),     0.3),
            # (MobilityEvaluator(), 0.1),
            # (KingActivityEvaluator(), 0.5),
        ]
    )

    tt = TranspositionTable()
    inner = AlphaBetaSearcher(evaluator, tt=tt)

    book_dir = os.path.join(os.path.dirname(__file__), "books")
    try:
        book = PolyglotBookReader.from_dir(book_dir)
        searcher = BookSearcher(inner, book)
    except FileNotFoundError:
        searcher = inner

    engine = Engine(searcher)
    uci = UCIHandler(engine)

    uci.run()


if __name__ == "__main__":
    main()
