#!/usr/bin/env -S python3 -u
from Fushi.engine import Engine
from Fushi.uci import UCIHandler
from Fushi.evaluate import ShannonEvaluator
from Fushi.search import BasicSearcher


def main():
    engine = Engine(BasicSearcher(ShannonEvaluator()))
    uci = UCIHandler(engine)

    uci.run()


if __name__ == "__main__":
    main()
